[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = [
    "go version",
    "ls -al",
    "go build -o app",
    "ls -al",          # setelah build, cek apakah app-nya muncul
]

[start]
cmd = "./app"
