[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = [
    "echo === BEFORE BUILD ===",
    "ls -al",
    "go version",
    "go build -o app",
    "echo === AFTER BUILD ===",
    "ls -al",
]

[start]
cmd = "chmod +x ./app && ./app"
